const colors = {
  light: {
    text: "#0F172A",
    tint: "#2563EB",
    background: "#F1F5F9",
    foreground: "#0F172A",
    card: "#FFFFFF",
    cardForeground: "#0F172A",
    primary: "#1D4ED8",
    primaryForeground: "#FFFFFF",
    secondary: "#E2E8F0",
    secondaryForeground: "#0F172A",
    muted: "#F1F5F9",
    mutedForeground: "#64748B",
    accent: "#059669",
    accentForeground: "#FFFFFF",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    border: "#CBD5E1",
    input: "#E2E8F0",
    warning: "#D97706",
    warningForeground: "#FFFFFF",
  },

  dark: {
    text: "#FFFFFF",
    tint: "#2563EB",
    background: "#0A1628",
    foreground: "#FFFFFF",
    card: "#1A2942",
    cardForeground: "#FFFFFF",
    primary: "#2563EB",
    primaryForeground: "#FFFFFF",
    secondary: "#1E3A5F",
    secondaryForeground: "#FFFFFF",
    muted: "#1A2942",
    mutedForeground: "#8B9DB5",
    accent: "#10B981",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2D3F5E",
    input: "#2D3F5E",
    warning: "#F59E0B",
    warningForeground: "#000000",
  },

  radius: 12,
};

export default colors;
