import { pgTable, uuid, text, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

// Replaces in-memory reassignmentHistory (ReassignmentRecord), append-only.
// No id in the source shape — synthetic UUID generated by the DB.
export const deploymentReassignmentHistoryTable = pgTable("deployment_reassignment_history", {
  id: uuid("id").primaryKey().defaultRandom(),
  vehicleId: text("vehicle_id").notNull(),
  vehicleNumber: text("vehicle_number").notNull(),
  unitCode: text("unit_code").notNull(),
  fromLocationId: text("from_location_id").notNull(),
  fromLocationName: text("from_location_name").notNull(),
  toLocationId: text("to_location_id").notNull(),
  toLocationName: text("to_location_name").notNull(),
  reassignedAt: timestamp("reassigned_at", { withTimezone: true }).notNull(),
  reassignedBy: text("reassigned_by"),
});

export const insertDeploymentReassignmentHistorySchema = createInsertSchema(
  deploymentReassignmentHistoryTable,
).omit({ id: true });
export type InsertDeploymentReassignmentHistory = z.infer<
  typeof insertDeploymentReassignmentHistorySchema
>;
export type DeploymentReassignmentHistory = typeof deploymentReassignmentHistoryTable.$inferSelect;
