import { pgTable, text, integer, check } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

// Replaces vapid.json — the original persistence gap (autogenerated on
// first boot, outside cloudPersistence.ts's sync list, so it regenerated
// on every restart). Singleton row (id is always 1).
export const vapidKeysTable = pgTable(
  "vapid_keys",
  {
    id: integer("id").primaryKey().default(1),
    publicKey: text("public_key").notNull(),
    privateKey: text("private_key").notNull(),
  },
  (table) => [check("vapid_keys_singleton_check", sql`${table.id} = 1`)],
);

export const insertVapidKeysSchema = createInsertSchema(vapidKeysTable);
export type InsertVapidKeys = z.infer<typeof insertVapidKeysSchema>;
export type VapidKeys = typeof vapidKeysTable.$inferSelect;
